---
- name: this playbook is for installing the required pakcages
  hosts: webserver
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
    notify: start httpd service
    
  handlers:  
  - name: start httpd service
    service:
      name: httpd
      state: started    
