---
- name: this playbook is for installing the required pakcages
  hosts: webserver
  become: true
  tasks:
  
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
  - name: un-install package
    yum:
      name: httpd
      state: removed	
